branch-defaults:
  default:
    environment: Turnpageprod-env
    group_suffix: null
  develop:
    environment: Turnpageprod-env
global:
  application_name: turnpage-prod
  branch: null
  default_ec2_keyname: tp-eb2
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
